name: CI/CD Pipeline


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Prepare Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17


      - name: Build Application
        run: go build -v ./...


      - name: Run Test
        run: go test -v ./...


      - name: Authenticate to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: niputuputri/learnci-cd:latest