name: CI/CD Pipeline


on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Prepare Go Environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.17


      - name: Build Application
        run: go build -v ./...


      - name: Run Test
        run: go test -v ./...


      - name: Authenticate to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: niputuputri/learnci-cd:latest

#       cd /home/siput/learnCI-CD

# USERNAME: siput
# PASSWORD: xxxxxxxx
# HOST: 0.tcp.ap.ngrok.io
# PORT: 14728

# ssh userDebbian@host -p port
# ssh siput@0.tcp.ap.ngrok.io -p 14728
      
      - name: SSH Login and Deployment
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/siput/learnCI-CD
            git pull origin main
            docker compose -f docker-compose.yml down
            docker pull niputuputri/learnci-cd

